# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"

- task: AzureCLI@2
  inputs:
    azureSubscription: 'uamangedidentity'
    scriptLocation: 'inlineScript'
    scriptType: pscore
    inlineScript: |
      az role assignment create --assignee "14443cd6-cd40-4f6e-97e5-c25d071c2029" --role "User Access Administrator" --scope "/subscriptions/72d61747-b97c-4857-9cc7-04bf2cdd552f"